" Auto-install vim-plug (ref: https://github.com/junegunn/vim-plug/wiki/tips#automatic-installation)
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
Plug '~/.vim-sensible'
Plug '~/.vim-sleuth'
Plug '~/.fzf'
call plug#end()

set background=dark
set number relativenumber
let g:fzf_preview_window = ['down:50%', 'ctrl-/']
nnoremap <silent> <C-p> :FZF<CR>
nnoremap <silent> <C-f> :Rg<CR>
